### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Thealexbarney** [Thealexbarney/LibHac#1]
- [ ] Documentation
- [ ] hactoolnet: Extract only the files that were changed in a patch
- [x] Trim unused save data bytes
- [x] Complete save data FS editing
- [x] XCI reading
- [x] Savefile reading
- [x] Bucket Tree integrity verification
- [x] Signature verification
- [x] NCA ExeFS automatic detection
- [x] NPDM reading
- [x] Read additional data from patch Content Meta binaries
- [x] Control.nacp reading
- [x] Key derivation
- [x] hactoolnet: Fail when a key is missing or when an integrity check fails
- [x] IFileSystem, IFile and IDirectory interfaces
- [x] 6.2.0 Key derivation

**Comment by CaitSith2** [comment]
Handle multi-part NAX0/NCA files.  (When such files are multi-part, they are split along the 0xFFFF0000 boundary, mainly to handle being able to copy the files from an exfat formatted SD card to a fat32 formatted SD card.)  Multi-part NCA files exist on the User NAND for games larger than 4GB, and Multi-part NAX0 on SD cards for the same reason.
